### PR TITLE
Bug fixes / context refactor

### LINKED ISSUE #16: With Snowflake, a query with no results gives an error when converting LongToWide, even though `ErrNoRows` is checked.

### LINKED ISSUE #28: Add Context and timeout

### LINKED ISSUE #31: Refactor away `github.com/pkg/errors` in favor of `errors`

### PR DESCRIPTION
**Pull request by kminehart**
Fixes #16 

Before:

image

After:

image

Also includes fixes:

* No more using `github.com/pkg/errors`, instead we just use the standard library `errors` package with `fmt.Errorf`.
    * fixes #31
* Adds context and context.WithTimeout to allow drivers to define a timeout based on the data source settings.
    * fixes #28 

This does include a breaking change because of the new function on the interface.

### CODE REVIEW

File: query.go [hunk 1]
```diff
@@ -90,22 +91,44 @@ func getErrorFrameFromQuery(query *Query) data.Frames {
...
+
+	select {
+	case <-done:
+		// The done channel will receive data if the query funciton has completed
+		return res, err
+	case <-ctx.Done():
+		// The context's done channel will receive data if the timeout is exceeded
+		return nil, ErrorTimeout
+	}
+}
```
Comment (andresmgot) [inline query.go:114]: isn't this `ctx` handling given for free just using `db.QueryContext`? (I may be looking to the wrong place but it seems handled the same way [here](https://cs.opensource.google/go/go/+/refs/tags/go1.17:src/database/sql/ctxutil.go;l=57;drc=refs%2Ftags%2Fgo1.17))

File: query.go [hunk 2]
```diff
@@ -139,6 +162,16 @@ func getFrames(rows *sql.Rows, limit int64, converters []sqlutil.Converter, fill
...
 
+	count, err := frame.RowLen()
+
+	if err != nil {
+		return nil, err
+	}
+
+	if count == 0 {
+		return nil, ErrorNoResults
+	}
```
Comment (andresmgot) [inline query.go:173]: it'd be also great to have some test for this, since this is the fix of #16

**Review by andresmgot — COMMENTED** [review]
I have some minor comments, let me know what you think!

File: driver.go [hunk 3]
```diff
@@ -13,7 +14,9 @@ import (
 type Driver interface {
 	// Connect connects to the database. It does not need to call `db.Ping()`
 	Connect(backend.DataSourceInstanceSettings) (*sql.DB, error)
+	Timeout(backend.DataSourceInstanceSettings) time.Duration
 	FillMode() *data.FillMissing
 	Macros() Macros
 	Converters() []sqlutil.Converter
+	// Timeout is used when sending a query to the backing data source. If the timeout is exceeded, the QueryData function will return an error.
```
[the remark this answers is not in the document]
Comment (kminehart) [reply driver.go:21]: Yeah, oops!

File: datasource.go [hunk 4]
```diff
@@ -102,21 +108,35 @@ func (ds *sqldatasource) handleQuery(req backend.DataQuery) (data.Frames, error)
...
+
+	// This function will return an "ErrorTimeout" if the context's done channel receives data
+	res, err := queryContext(ctx, ds.db, ds.c.Converters(), fillMode, q)
 	if err == nil {
 		return res, nil
 	}
 
-	if errors.Cause(err) == ErrorQuery {
+	if errors.Is(err, ErrorNoResults) {
+		return nil, nil
```
[the remark this answers is not in the document]
Comment (kminehart) [reply datasource.go:130]: Nope, returning `nil, nil` in the handler will show a graph that shows "No results".

File: query.go (hunk 1 above)
Comment (kminehart) [reply query.go:114]: You may be right... if the context is cancelled then the `QueryContext` function may just return an error. I'll look into this.

File: driver.go [hunk 5]
```diff
@@ -13,7 +14,9 @@ import (
 type Driver interface {
 	// Connect connects to the database. It does not need to call `db.Ping()`
 	Connect(backend.DataSourceInstanceSettings) (*sql.DB, error)
+	Timeout(backend.DataSourceInstanceSettings) time.Duration
```
Comment (yesoreyeram) [inline driver.go:17]: Do we need this to be explicit like `QueryTimeout`? We may have to add `ConnectionTimeout` in the future.

Comment (kminehart) [reply driver.go:17]: Actually that gives me another idea. Good call though

File: datasource.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (kminehart) [reply datasource.go]: good comment, I changed this to return an empty frame with meta instead of nil.

**Review by andresmgot — APPROVED** [review]
LGTM. I'd be great to have more tests but don't want to block this PR for that.

**Comment by kminehart** [comment]
> LGTM. I'd be great to have more tests but don't want to block this PR for that.

I'm with you but I think I want to do some refactoring to make this more testable first :see_no_evil:
